// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDV4MsNsWbtvdG6yd8kraOV0oGxzvpYoQg',
    appId: '1:88691864012:web:57229c5029cbfb4a416d69',
    messagingSenderId: '88691864012',
    projectId: 'zippapp-db',
    authDomain: 'zippapp-db.firebaseapp.com',
    storageBucket: 'zippapp-db.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAM6icvnZf6Qh9kVGe59zfJIx4uB__LYbk',
    appId: '1:88691864012:android:9b188d4e1baa0eb3416d69',
    messagingSenderId: '88691864012',
    projectId: 'zippapp-db',
    storageBucket: 'zippapp-db.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3pev9vp5Zud4Nb_uqa95eGNlJY7y16lU',
    appId: '1:88691864012:ios:2e8329c14adeb69c416d69',
    messagingSenderId: '88691864012',
    projectId: 'zippapp-db',
    storageBucket: 'zippapp-db.firebasestorage.app',
    iosBundleId: 'com.example.zippFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3pev9vp5Zud4Nb_uqa95eGNlJY7y16lU',
    appId: '1:88691864012:ios:2e8329c14adeb69c416d69',
    messagingSenderId: '88691864012',
    projectId: 'zippapp-db',
    storageBucket: 'zippapp-db.firebasestorage.app',
    iosBundleId: 'com.example.zippFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDV4MsNsWbtvdG6yd8kraOV0oGxzvpYoQg',
    appId: '1:88691864012:web:371bfeb014f750bf416d69',
    messagingSenderId: '88691864012',
    projectId: 'zippapp-db',
    authDomain: 'zippapp-db.firebaseapp.com',
    storageBucket: 'zippapp-db.firebasestorage.app',
  );

}